// OpenCode adapter. Verified 2026-10-01 (https://opencode.ai/docs/plugins/ and the plugin types in
// packages/plugin/src/index.ts): a plugin in .opencode/plugins/ gets
//   "tool.execute.before"(input: { tool, sessionID, callID }, output: { args }) — throwing blocks the call
//   "tool.execute.after"(input: { tool, sessionID, callID, args }, output: { title, output, metadata })
// kerb init writes a small plugin that pipes these to `kerb hook opencode pre|post` and throws
// Kerb's refusal text on a deny.
import { observePre, observePost, callId } from './observe.js';
import { SHELL_TOOLS, exitFromText, exitField, argsObject, commandOf, resolveCwd, refusalText, noteLines } from './shared.js';

export const AGENT = 'opencode';

export function pre(ctx, p) {
  if (!SHELL_TOOLS.has(p.tool)) return null;
  const args = argsObject(p.args);
  const command = commandOf(args);
  if (!command) return null;
  const cwd = resolveCwd(p.cwd || ctx.cwd, args.workdir || args.cwd);
  const r = observePre(ctx, { agent: AGENT, command, cwd, toolUseId: callId(p.callID, p.sessionID, cwd, command), session: p.sessionID || null, agentTimeoutMs: Number(args.timeout) || null });
  if (r.refusal) return { deny: refusalText(r.refusal) };
  return null;
}

export function post(ctx, p) {
  if (!SHELL_TOOLS.has(p.tool)) return null;
  const args = argsObject(p.args);
  const command = commandOf(args);
  if (!command) return null;
  const cwd = resolveCwd(p.cwd || ctx.cwd, args.workdir || args.cwd);
  const explicit = exitField(p.metadata);
  const text = typeof p.output === 'string' ? p.output : '';
  const exit = explicit !== null ? explicit : exitFromText(text);
  const r = observePost(ctx, { agent: AGENT, toolUseId: callId(p.callID, p.sessionID, cwd, command), cwd, command, exit, output: text, session: p.sessionID || null });
  const lines = noteLines(r.notes, r.hints);
  return lines.length ? { context: lines.join('\n') } : null;
}

export function startOutput() { return null; }
export function stopOutput() { return null; }

/** The plugin file kerb init writes to .opencode/plugins/kerb.js. */
export function pluginSource(argv) {
  return `// Generated by kerb init. It contains absolute paths for this machine; kerb uninstall removes it.
import { spawnSync } from "node:child_process";

const KERB = ${JSON.stringify(argv)};

function call(event, payload) {
  try {
    const r = spawnSync(KERB[0], [...KERB.slice(1), "hook", "opencode", event], {
      input: JSON.stringify(payload),
      encoding: "utf8",
      timeout: 5000,
    });
    const out = (r.stdout || "").trim();
    return out ? JSON.parse(out) : null;
  } catch {
    return null; // Kerb fails open.
  }
}

export const Kerb = async ({ directory }) => ({
  "tool.execute.before": async (input, output) => {
    if (input.tool !== "bash") return;
    const r = call("pre", { tool: input.tool, sessionID: input.sessionID, callID: input.callID, args: output.args, cwd: directory });
    if (r && r.deny) throw new Error(r.deny);
  },
  "tool.execute.after": async (input, output) => {
    if (input.tool !== "bash") return;
    call("post", { tool: input.tool, sessionID: input.sessionID, callID: input.callID, args: input.args, cwd: directory, output: output.output, metadata: output.metadata });
  },
});
`;
}
